# Generated by Django 3.2.8 on 2021-10-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_api_app', '0002_auto_20211022_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_vendor',
        ),
    ]
