# Generated by Django 3.2.8 on 2021-10-22 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_api_app', '0003_remove_product_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_vendor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
