# Generated by Django 3.2.8 on 2021-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_api_app', '0004_product_product_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
